version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pesq-hub-app
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html
      - ./storage/app/credenciais.json:/var/www/html/storage/app/credenciais.json:ro
      # Excluir diretórios que precisam de permissões específicas
      - /var/www/html/storage/framework
      - /var/www/html/storage/logs
      - /var/www/html/bootstrap/cache
      # Volume anônimo para vendor - evita sobrescrever dependências instaladas
      - /var/www/html/vendor
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:lxGdhXlEGhx7mpT+rRY84VuXQUP5iFd/M1hH9AflMQU=
      - APP_URL=http://localhost:8001
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=pesq_hub
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - SESSION_DRIVER=database
      - CACHE_STORE=database
      - QUEUE_CONNECTION=database
      - GOOGLE_CLIENT_ID=955527164761-1hg260j8v3bm9cge133hpd8q0vmtbiv0.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GOOGLE_REDIRECT_URI=http://localhost:8001/google/callback
      - GOOGLE_APPLICATION_CREDENTIALS=credenciais.json
      - GOOGLE_SHEET_ID=15jSuekgRohhMeDE6uzyne_2jDb-V0lZkg5yiEkWsv80
    restart: unless-stopped
    networks:
      - pesq-hub-network

  db:
    image: postgres:15-alpine
    container_name: pesq-hub-db
    environment:
      POSTGRES_DB: pesq_hub
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - pesq-hub-network
    restart: unless-stopped

volumes:
  db_data:
    driver: local

networks:
  pesq-hub-network:
    driver: bridge
