
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pesq-hub-app
    env_file:
      - .env
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - ./storage/app/credenciais.json:/var/www/html/storage/app/credenciais.json:ro
      # Excluir diretórios que precisam de permissões específicas
      - /var/www/html/storage/framework
      - /var/www/html/storage/logs
      - /var/www/html/bootstrap/cache
    depends_on:
      - db
    environment:
      # Sobrescreve variáveis específicas do ambiente Docker
      - DB_HOST=db
      - DB_PORT=5432
    restart: unless-stopped
    networks:
      - pesq-hub-network

  db:
    image: postgres:15-alpine
    container_name: pesq-hub-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - pesq-hub-network
    restart: unless-stopped

volumes:
  db_data:
    driver: local

networks:
  pesq-hub-network:
    driver: bridge
